//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lanit3.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class car
    {
        public long Id { get; set; }
        public string model { get; set; }
        public int horsepower { get; set; }
    
        public virtual person person { get; set; }
    }
}
